.babelrc
.eslintrc
.gitignore
.travis.yml
README.md
__tests__/BottomWordCard.test.js
__tests__/Container.test.js
__tests__/DropBoxArea.test.js
__tests__/DropBoxItem.test.js
__tests__/TopWordCard.test.js
__tests__/WordBankArea.test.js
__tests__/WordBankItem.test.js
package-lock.json
package.json
src/Container.js
src/components/DropBoxArea/index.js
src/components/DropBoxItem/BottomWordCard.js
src/components/DropBoxItem/TopWordCard.js
src/components/DropBoxItem/index.js
src/components/WordBankArea/index.js
src/components/WordBankItem/index.js

This adds support for tests, coverage, and linting.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/word-alignment-tool/3)

Tests and coverage

---

src/components/DropBoxArea/index.js
src/components/DropBoxItem/index.js
src/components/WordBankArea/index.js
src/helpers/lexiconHelpers.js

- Unmerge with Blank alignment after current
- Unmerge without empty alignment persisted
- Check out the same branch of the tC app
- Open a project to align AFTER deleting the existing alignment data
- Drag and drop empty greek words to conjoin
- Drag and drop a conjoined greek word to the new empty alignment that pops up
- Do the same after dropping word bank words into each
- Ensure all functions as expected
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/word-alignment-tool/9)

Unmerge with Blank alignment after current

---

package.json

This pull request addresses:
Issue #2806 - Provides better description for Word alignment tool
How to test this pull request:
See the card for Word alignment tool. Should say A tool to align the translation with the original biblical languages in order to show how the translation communicates the meaning represented in the original. This data can be useful in creating other resources such as concordances and interlinear Bibles in the target language. instead of Word alignment tool
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/word-alignment-tool/11)

Feature - #2806 - Changes description of Word Alignment Tool

---

src/components/DropBoxItem/TopWordCard.js
src/components/WordDetails.js
src/helpers/lexiconHelpers.js

Corrected strongs to strong
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/word-alignment-tool/19)

Feature mcleanb #3186/Switch to strongs. 

---

src/components/DropBoxItem/TopWordCard.js
src/components/WordDetails.js
src/helpers/lexiconHelpers.js

Lots of USFM changes from importing to exporting to alignment data, and usage in tools.
Requires checking out branches from `translationCore`, `ScripturePane` and `WordAlignmentTool`.
Test the entire app make sure all works as intended.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/word-alignment-tool/20)

Sandbox feature usfm3

---

package-lock.json
package.json
src/components/Container.js

- This PR exchanges the package isEqual for deep-equal, per request of klappy from my PR regarding word alignment errors #3906.
run the following script in the root folder to get all the branches needed.
`git checkout feature-jay-3973 && git pull; cd tC_apps/ScripturePane; git checkout feature-jay-3973 && git pull; cd ../VerseCheck; git checkout feature-jay-3973 && git pull; cd ../wordAlignment; git checkout feature-jay-3973 && git pull; cd ../../;`
- Run the app and make sure everything works as expected
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/wordalignment/26)

changed isEqual to deep-equal

---

package-lock.json
src/components/PrimaryWord.js
src/components/WordDetails.js

- Fixed lexicon loafing bug
- **Dependencies:**
- https://github.com/unfoldingWord-dev/translationCore/pull/4098
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/wordalignment/29)

Fixed lexicon loading bug

---

.travis.yml
gulpfile.js
package-lock.json
package.json

- This update will upload the English locale to a Crowdin project for localization.
- Merge into master and watch the magic.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/wordalignment/32)

Connect Crowdin

---

src/components/Container.js
src/components/WordList/index.js

-
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/wordalignment/40)

Word List Height Fix

---

package.json

-
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/wordalignment/42)

Removed now unnecessary include key from package.json

---

package.json
src/components/Container.js
src/utils/panesSettingsHelper.js

-
- See: https://github.com/unfoldingWord-dev/translationCore/pull/4657
- https://github.com/unfoldingWord-dev/translationCore/pull/4657
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/wordalignment/45)

Addressed QA issues for 4520

---

src/utils/usfmHelpers.js

-
- Open [rev.usfm.zip](https://github.com/translationCoreApps/wordAlignment/files/2172181/rev.usfm.zip) and go to Rev 5:12 and make sure that you don't see a letter i in the word list like in the example below.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/wordalignment/51)

Removing \pi marker as well

---

package-lock.json
package.json
src/Api.js
src/__tests__/api.js
src/components/Container.js
src/components/PrimaryToken.js
src/containers/GroupMenuContainer.js
src/state/actions/index.js
src/state/reducers/__mocks__/index.js
src/state/reducers/alignments/compile.js
src/state/reducers/alignments/verse.js
src/state/reducers/index.js

Related to https://github.com/unfoldingWord-dev/translationCore/issues/2258 and https://github.com/unfoldingWord-dev/translationCore/issues/4319 (incomplete)
- Adds support for tracking verse validation (not visible in UI yet)
- Refactored verse complete management
- Increases verse navigation performance (25% improvement!)
- Improves MAP snackbar consistency. 
> NOTE: I will need to make some adjustments to the group menu in the ui tool kit before the invalidation icon can be displayed in the menu.
Depends on https://github.com/unfoldingWord-dev/translationCore/pull/4723
- Verse validation state is stored in `.apps/translationCore/tools/wordAlignment/invalid/`
- Verse completion state is stored in `.apps/translationCore/tools/wordAlignment/completed/`
- After clicking the refresh button …

Verse validation, performance, MAP notifications

---

package-lock.json
src/Api.js

Related to https://github.com/unfoldingWord-dev/translationCore/issues/4803
- This fixes data getting lost when quickly setting an alignment in wA and then leaving the tool.
- Open a project in wA and make an alignment.
- As soon as you drop the word on an alignment quickly exit the tool using any of the top navigation tabs.
- After a few seconds re-open the project and the alignment should still exist.
Previously the above actions would corrupt the alignments for the entire book.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/wordalignment/65)

Fixed alignments being corrupted

---

src/Api.js
src/components/Container.js

-
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/wordalignment/71)

Created PR to merge Joel's fixes into 0.10.1 release.

---

package-lock.json
package.json
src/containers/ScripturePaneContainer.js

- Pass actions getAvailableScripturePaneSelections and makeSureBiblesLoadedForTool to ScripturePane
- test using https://github.com/unfoldingWord-dev/translationCore/pull/5034
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/wordalignment/77)

bugfix 5030/Support Minimal loaded languages

---

package-lock.json
src/state/reducers/alignments/__tests__/compile_alignments.test.js
src/state/reducers/alignments/__tests__/suggestions.test.js
src/state/reducers/alignments/compile.js

> Not for 1.0 release
This is related to https://github.com/unfoldingWord-dev/translationCore/issues/4957
- This correct a bug where you could not accent tokens in a suggestion group of three or more tokens.
- The easiest way to test this is to find two verses with a common word in the original language.
- Then edit the gateway language text in both verses adding the words "how are you" or something like that.
- Align those three words to the common original word in one of the verses.
- In the other verse you should now see the alignment suggestion with three words suggested.
- You should be able to click on the suggested words one at a time to accept them all.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Fixes bug in accepting alignment suggestions

---

src/Api.js

- Fixes an issue with dispatching numerous times within a for-loop
- Simply run tC with the fix and without and ensure that there are faster run times with it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/wordalignment/82)

Batched Actions For Verse Resets

---

src/components/Container.js

Related to https://github.com/unfoldingWord-dev/translationCore/issues/4940
- Fixes a corner case bug where the verse would not be automatically marked as complete when accepting an alignment suggestion.
- See linked issue for testing instructions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/wordalignment/83)

Fixed auto-complete bug

---

src/components/Container.js

-
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/wordalignment/86)

Release v1.0.2

---

package-lock.json
package.json
src/Api.js

Update master w/ changes in Release v1.0.2

---

src/components/AlignmentCard/AlignmentCard.js
src/components/AlignmentCard/__tests__/__snapshots__/AlignmentCard.test.js.snap
src/components/AlignmentCard/index.js
src/components/AlignmentGrid.js
src/components/Container.js
src/components/PrimaryToken.js
src/components/SecondaryToken.js
src/components/WordCard/__tests__/WordCard.test.js
src/components/WordCard/__tests__/__snapshots__/WordCard.test.js.snap
src/components/WordCard/index.js
src/components/WordList/WordList.js
src/components/WordList/__tests__/__snapshots__/DroppableWordList.test.js.snap
src/components/WordList/index.js
src/components/__tests__/__snapshots__/AlignmentGrid.test.js.snap

Related to https://github.com/unfoldingWord-dev/translationCore/issues/3655 and https://github.com/unfoldingWord-dev/translationCore/issues/5197
- Text direction in the alignments now reflects the language direction.
- Source and target text directions work independently.
- Word list supports language direction as well.
- There is no rtl source text yet, but you can manually change the text direction by modifying the react properties. See example gif below.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/wordalignment/104)

Adds language support to alignments

---

package-lock.json
package.json
src/locale/English-en_US.json

- This PR completes the scripture pane localization story by adding the necessary localization to both tools
- Make sure that the Scripture Pane Headings are localized in the app
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/wordalignment/109)

Added New Locale Keys and Updated tc-ui-toolkit Version

---

src/components/AlignmentCard/index.js
src/components/AlignmentGrid.js
src/components/Container.js
src/components/PrimaryToken.js
src/components/__tests__/__snapshots__/AlignmentGrid.test.js.snap

Related to https://github.com/unfoldingWord-dev/translationCore/issues/5789
- Increases the font size of Hebrew in the alignment cards.
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/wordalignment/158)

Increases hebrew font size

---

package-lock.json
package.json
src/containers/GroupMenuContainer.js

Related to https://github.com/unfoldingword-dev/translationcore/issues/5710
- Adds the updated menu
- corrected the order of icons in the menu items.
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/wordalignment/160)

Updated menu styles

---

src/Api.js
src/__tests__/api.js

- adds optional parameter for silent validation check
- adds fix to return validation results
- test using https://github.com/unfoldingWord-dev/translationCore/pull/5962
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/wordalignment/173)

Enhancement mcleanb 5941

---

package-lock.json
package.json
src/components/AlignmentCard/__tests__/dragDrop.test.js
src/components/AlignmentCard/index.js
src/components/PrimaryToken.js
src/state/actions/__tests__/actions.test.js
src/state/actions/index.js
src/state/reducers/alignments/__tests__/alignments.test.js
src/state/reducers/alignments/__tests__/render_alignments.test.js
src/state/reducers/alignments/__tests__/suggestions.test.js
src/state/reducers/alignments/index.js
src/state/reducers/alignments/render.js

- canDropPrimaryToken() - removed drop limitation to adjacent alignments
- dragHandler.canDrag() - removed limitation that you can only drag from first or last entry.
- fixed alignments rendering to support discontiguous alignments
- added unit test for discontiguous alignments in render.
- here are test builds you can try - see most recent builds in http://tc-builds.door43.org.s3-website-us-west-2.amazonaws.com/build/release-v1.2.0-testing/
- look at the specs in https://github.com/unfoldingword-dev/translationcore/issues/4791.  Open up a project in WA tool and you should be able to do operations in spec 1 to 3 in all sorts of combinations and spec 4 to 5 should stay consistent.  Also should not lose Greek words or see duplicates.  Also keep an eye on console - will see alignment errors …

Feature 4791/unalign any primary word and move any primary word to any other alignment

---

src/components/AlignmentCard/index.js
src/components/AlignmentGrid.js
src/components/Container.js
src/components/PrimaryToken.js

- Tweak font size in Alignment area for use with new font
- ~This needs to be merged first: https://github.com/unfoldingWord-dev/translationCore/pull/6180~ Merged
- test with latest develop
- in WA tool the Hebrew characters in alignment area should be the same size as ScripturePane.  Also lexicon popups should be same size.  Open an OT book to verify. Example from Ezra:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/wordalignment/184)

Feature 6089/Tweak font size in Alignment area for use with new font

---

src/Api.js
src/components/Container.js
src/utils/SimpleCache.js
src/utils/migrations.js

Related to https://github.com/unfoldingWord-dev/translationCore/issues/5662
- Adds support for using alignment memory across an entire language.
- make some alignments in a project.
- open another project that has the same language and translation identifier (resource id).
- Your previous alignments should appear as suggestions where appropriate inside of the second project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/wordalignment/185)

Global alignment memory

---

src/components/MAPControls.js
src/components/__tests__/__snapshots__/MAPControls.test.js.snap

-
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/wordalignment/190)

Changed non-standard colors to standard colors

---

package-lock.json
package.json
src/components/Container.js
src/components/WordList/__tests__/DroppableWordList.test.js
src/components/WordList/__tests__/WordList.test.js
src/components/WordList/__tests__/__snapshots__/DroppableWordList.test.js.snap
src/components/WordList/index.js
src/containers/ScripturePaneContainer.js

- Fixes Problem # 1 and # 2 in https://github.com/unfoldingWord-dev/translationCore/issues/5930 (implements both solutions given by Ben)
- Allows passing of (optional) function from the Container to the ScripturePane (tc-ui-toolkit) to handle when a modal is opened (true) or closed (false)
- Unit tests should pass
- To test in tC, update to latest version of develop, change tc-ui-toolkit to `0.14.22` in tC's `package.json` and `npm install` in tC root. Check out this branch in `tC_apps/wordAlignment`. Open tC, open project, open WA. 
- Click some words in the word bank, then change to another verse, you shouldn't see words at the positions you click to still be blue (Issue #5930 Problem # 1).
- Click some words in the word bank, then click the Scripture Pane expand button, then close the …

Fixes #5930 - clear activated words in word bank

---

package-lock.json
src/components/MAPControls.js
src/components/__tests__/__snapshots__/MAPControls.test.js.snap

- Make sure both toggle/switch components have the same styling 
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/wordalignment/199)

Fixed Dissimilarities between the Bookmark switch and the Alignment Complete switch

---

package-lock.json
package.json

- Brings in rendering performance improvements for wA
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/wordalignment/200)

Added Scripture Pane Performance Improvements

---

src/components/Container.js

- fixes for quote arrays in alignment memory.
- test with tCore branch bugfix-mcleanb-6380
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/wordalignment/202)

Bugfix 6380/fixes for quote arrays in alignment memory.

---

src/components/SecondaryToken.js

- For #5201, solution option #2 to have the mouse icon change to a waiting icon for a second. The delay is due to the event listener having to be attached, needing time, so option #1 was not an option in all the things I tried.
- Checkout this branch in wA and use the latest develop branch of tC, run tC, go into the wordAlignment tool, click a word in the word list that is not selected. You should see the mouse cursor change for that button to the wait cursor and then in 1 second change back to a pointer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/wordalignment/203)

Fix for clicking word list items with a delay

---

src/Api.js
src/utils/verseObjects.js

-
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/wordalignment/205)

Performance Improvement of Token Instantiation Array.map

---

package-lock.json
package.json

-
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/wordalignment/210)

added performance improvement of wordmap lexer

---

index.js

- Pending https://github.com/translationCoreApps/checking-tool-wrapper/pull/53
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/wordalignment/216)

Removed enablebatching (Its now enabled inside tc-tool module)

---

src/Api.js

- make sure alignment memory uses resource ID in lower case
- can use the attached test build.
- follow process in https://github.com/unfoldingword/translationcore/issues/6534 and should see suggestions for Zec project in wA

Bugfix 6534/make sure alignment memory uses resource ID in lower case

---

package-lock.json
src/Api.js
src/__mocks__/fs-extra.js
src/__tests__/api.js
src/components/AlignmentGrid.js
src/components/Container.js
src/components/IconIndicators/index.js
src/components/MAPControls.js
src/components/__tests__/__snapshots__/MAPControls.test.js.snap
src/containers/GroupMenuContainer.js
src/locale/English-en_US.json
src/state/actions/actionTypes.js
src/state/reducers/groupMenu.js
src/utils/CheckDataHelper.js
src/utils/__tests__/CheckDataHelper.test.js

- WA Alignment area Title bar with indicators.  Indicators now show verse edits, bookmarks, comments.  But not yet a way to add bookmarks, comments to verses (later issue).
- GroupMenu icons will now show verse edits, bookmarks, comments.  
- GroupMenu filter will now work for verse edits, bookmarks, comments. 
- This is the first UI part of the Epic - adds the toolbar with displayed actions and connects the group menu.  Making icons actionable comes later.
- Here is a test project that has a bookmark and comment for testing: [en_alcz_tit_book 2.zip](https://github.com/unfoldingWord/translationCore/files/4015599/en_alcz_tit_book.2.zip)
- Use test build attached below.
- open the above project in WA tool.
- test filter for each of these - verse edit, comments, bookmarks:
- make sure align …

Feature 5406/Add UI for WA Alignment area Title bar with indicators

---

src/utils/CheckDataHelper.js

- fix timestamped filename in writeCheckData so we don't fail in Windows.
- Test builds are here: https://github.com/unfoldingWord/translationCore/actions/runs/33105549

Bugfix 5409/fix for saving WA checks in Windows

---

src/components/Container.js

- fix type warning in console
-

Bugfix 5409/Fix type warning in console

---

src/Api.js
src/components/Container.js
src/containers/GroupMenuContainer.js

-
[projects.zip](https://github.com/unfoldingWord/translationCore/files/4207226/projects.zip)
1. Unzip the projects into the projects folder
2. Restart tC
3. Select the Acts project and load it into wA
4. Return to the Projects screen
5. Select the Titus project and load it into wA
> The critical error screen should not be displayed.
1. Import https://git.door43.org/qa99/abu_tit_reg
2. Load the project in tW
> The critical error screen should not be displayed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/wordalignment/250)

Fixed Critical error when opening a project

---

package-lock.json
package.json
src/components/SecondaryToken.js

- fix wordAlignment Tool drag preview
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/wordalignment/256)

Bugfix 6730/Fix Images shown in wA

---

src/components/Container.js

- fix scripture pane wrapper so it won't shrink vertically
- fix alignment grid so it fills available space
-  checkout tCore branch `bugfix-mcleanb-6731.2`.  Do `rm -rf ./node_modules && npm ci && npm run load-apps && npm start`
- open wa, tw and tn tools to make sure that layout is not broken.  See https://github.com/unfoldingword/translationcore/issues/6731
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/wordalignment/258)

Bugfix 6731/Fix tool layout

---

index.js

-
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/wordalignment/262)

Paths fixes for build process

---

package-lock.json
src/components/AlignmentGrid.js
src/components/Container.js
src/components/__tests__/__snapshots__/AlignmentGrid.test.js.snap

-
- Test using https://github.com/unfoldingWord/translationCore/pull/6842
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/wordalignment/263)

CSS layout fixes

---

index.js
package-lock.json
package.json
src/common/constants.js
src/components/AlignmentGrid.js
src/components/Container.js
src/components/SecondaryToken.js
src/components/__tests__/__snapshots__/AlignmentGrid.test.js.snap
src/locale/nonTranslatable.js
src/locale/nonTranslatable.json
src/state/actions/contextIdActions.js
src/state/selectors.js

- merged the sandbox-electronite into develop
- test with tCore branch `merge-sandbox` (https://github.com/unfoldingWord/translationCore/pull/6844)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/wordalignment/264)

Merge sandbox

---

src/state/reducers/alignments/__tests__/render_alignments.test.js
src/state/reducers/alignments/render.js

- Related to https://github.com/unfoldingword/translationcore/issues/6798
- Fixes a bug where some alignments could get lost during the rendering process.
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/wordalignment/269)

Fix losing alignments

---

src/common/fontUtils.js
src/components/AlignmentCard/__tests__/__snapshots__/AlignmentCard.test.js.snap
src/components/AlignmentCard/index.js
src/components/AlignmentGrid.js
src/components/Container.js
src/components/SecondaryToken.js
src/components/WordCard/__tests__/__snapshots__/WordCard.test.js.snap
src/components/WordCard/index.js
src/components/WordList/WordList.js
src/components/WordList/__tests__/__snapshots__/DroppableWordList.test.js.snap
src/components/WordList/__tests__/__snapshots__/WordList.test.js.snap
src/components/WordList/index.js
src/components/__tests__/__snapshots__/AlignmentGrid.test.js.snap

- ***`ATTENTION`: This PR is ready for code review and local testing but must be merged together with https://github.com/unfoldingWord/translationCore/pull/6949***
- Test with https://github.com/unfoldingWord/translationCore/pull/6949
- Make sure to checkout `feature-mannycolon-6935` for the wordAlignment tool
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/wordalignment/271)

Added target language font selection support

---

package-lock.json
package.json
src/common/fontUtils.js
src/components/Container.js

-
- Follow test instructions in https://github.com/unfoldingWord/translationCore/pull/6962#issue-427394776
- Merged with https://github.com/unfoldingWord/translationCore/pull/6962
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/wordalignment/274)

Renamed "language font" to "project font"

---

src/utils/usfmHelpers.js

- clean up removeUsfmMarkers() and remove code no longer needed.
- should not see any change in tC.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/wordalignment/277)

Bugfix 6847/Clean out old USFM code.

---

README.md
src/components/AlignmentCard/__tests__/__snapshots__/AlignmentCard.test.js.snap
src/components/AlignmentCard/index.js
src/components/AlignmentGrid.js
src/components/SecondaryToken.js
src/components/WordCard/__tests__/__snapshots__/WordCard.test.js.snap
src/components/WordCard/index.js
src/components/WordList/WordList.js
src/components/WordList/__tests__/__snapshots__/DroppableWordList.test.js.snap
src/components/__tests__/__snapshots__/AlignmentGrid.test.js.snap

-
- Follow test instructions in https://github.com/unfoldingWord/translationCore/pull/6976#issue-428460505
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/wordalignment/276)

Complex script font fixes

---

src/components/Container.js

- Related to https://github.com/unfoldingword/translationcore/issues/6957
- Corrects the css styles so the wordbank width does not shrink.
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/wordalignment/275)

fixes the width of the wordbank

---

src/components/AlignmentCard/__tests__/__snapshots__/AlignmentCard.test.js.snap
src/components/WordCard/__tests__/__snapshots__/WordCard.test.js.snap
src/components/WordCard/index.js
src/components/WordList/WordList.js
src/components/WordList/__tests__/__snapshots__/DroppableWordList.test.js.snap
src/components/WordList/__tests__/__snapshots__/WordList.test.js.snap
src/components/__tests__/__snapshots__/AlignmentGrid.test.js.snap

- Related to https://github.com/unfoldingword/translationcore/issues/6957
- Fixes some strange artifacts while dragging words.
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/wordalignment/279)

fixed word drag

---

package-lock.json
package.json
src/components/Container.js
src/utils/panesSettingsHelper.js

- Use https://github.com/unfoldingWord/translationCore/pull/7026 to test
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/wordalignment/286)

Addressed QA fail issues with target language text resizing

---

src/containers/GroupMenuContainer.js

- remove book name from group menu
- in tn and tw group menu overflows should show like this in rtl languages.  And group menu entries should not have book name:
- and for ltr languages:
- in WA group menu should show like this without book name in rtl languages:
- and for ltr languages:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/wordalignment/287)

Bugfix 6988/Remove book names from group menu items

---

src/containers/ScripturePaneContainer.js
src/locale/English-en_US.json

-
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/wordalignment/289)

Updated Locale & now passing necessary props for new font selection feature

---

src/components/Container.js

- added with font sizing for verse editor
- merge this after PR https://github.com/unfoldingWord/translationCore/pull/7050
- use build attached to https://github.com/unfoldingWord/translationCore/pull/7050
- in wA, text size in verse editor should match text size in alignment grid area:
- in enhanced scripture pane, text size  in verse editor should match text size in target language pane:
- in tW and tN, text size in verse editor should match text size in selection area:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/wordalignment/288)

Feature 7038/Make verse edit fonts resizable

---

src/containers/ScripturePaneContainer.js

-
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/wordalignment/291)

Added new font selection feature to scripture pane resources

---

package-lock.json
package.json
src/components/ThreeDotMenu.js
src/components/WordList/__tests__/__snapshots__/DroppableWordList.test.js.snap

- changed ThreeDotMenu to use absolute positioning based on initial three dot menu position.
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/wordalignment/292)

Bugfix 7028/Make Word Bank font sizer stationary
