src/Container.js, src/components/DropBoxArea/index.js, src/components/DropBoxItem/TopWordCard.js, src/components/DropBoxItem/index.js, src/components/WordDetails.js, src/helpers/lexiconHelpers.js
This PR adds the same popovers from the scripture pane to the word alignment tool.
Make sure when you click on a greek word in the black box the pop over shows with expected data.
(data is expected to be the same as the scripture pane would show)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/word-alignment-tool/4)
=> Added Info Popovers To Greek Words

src/components/WordBankArea/index.js
- Made the word bank area a drop zone to allow wordBankItems to be moved back to it.
- Added actions that perform the word bank item moving
- Test with https://github.com/unfoldingWord-dev/translationCore/pull/2844
- Try dragging words from the greek area back to the word bank area.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/word-alignment-tool/5)
=> Drag words back to the word bank area

src/components/DropBoxArea/index.js, src/components/DropBoxItem/BottomWordCard.js, src/components/DropBoxItem/TopWordCard.js, src/components/DropBoxItem/index.js, src/components/ItemTypes.js, src/components/WordBankItem/index.js
Merging TopWords and aligned bottom words
- Checkout the same branch in the translationCore repo.
- Test the dragging and dropping of Top words.
- Should be droppable one to the left and to the right of it.
- Should not be droppable on any others.
- Test pre-existing drag and drop functionality of word bank and bottom words.
- Test the dragging and dropping of Top Words that include bottom words.
- Should merge all bottom words.
- Dragging TopWords that are already merged will merge all pre-merged alignments.
- This will be addressed after unmerging Top Words as that is a prerequisite.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/word-alignment-tool/6)
=> Merging TopWords and aligned bottom words

src/Container.js
- Updated `UGNT` reference to `BHP`
- Delete the resources folder from the `translationCore` folder in the user directory.
- Then open a tool and you should not be able to load UGNT in the scripture pane
- This PR should be tested together with:
https://github.com/unfoldingWord-dev/translationCore/pull/2856
https://github.com/translationCoreApps/tC_Resources/pull/7
https://github.com/translationCoreApps/word-alignment-tool/pull/7
https://github.com/translationCoreApps/ScripturePane/pull/66
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/word-alignment-tool/7)
=> Updated `UGNT` reference to `BHP`

src/components/DropBoxArea/index.js, src/components/DropBoxItem/TopWordCard.js, src/components/DropBoxItem/index.js
Unmerging TopWords in Alignment
- Drag and drop TopWords in alignment and see if they behave as expected, including sorting.
- Drag and drop BottomWords and ensure they work as before/expected.
- Should Sort properly now.
- Drag TopWords together after BottomWords are aligned.
- Should merge BottomWords from both if the Dragged TopWord was solo.
- Should reset BottomWords from both if Dragged TopWord was not solo.
- Drag a Merged TopWord to the blank Alignment at the bottom.
- Should unmerge it and reset BottomWords from where it came.
- Should properly sort the TopWords.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/word-alignment-tool/8)
=> Unmerging TopWords in Alignment

src/components/DropBoxArea/index.js, src/components/DropBoxItem/index.js, src/components/WordBankArea/index.js
Don't show empty alignment if sibling doesn't have enough to take away
Must test independently of the other matching PR.
This was addressed fundamentally in the core actions and also in the tool UI.
Tool fix addresses root behavior, tool fix prevents it from happening
- Drag a TopWord that is solo an no empty alignment should show up anymore
- Test existing functionality to ensure other use cases weren't broken.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/word-alignment-tool/10)
=> Don't show empty alignment if sibling doesn't have enough to take away

src/Container.js
- Now setting the scripture pane to display targetLanguage, then bhp and at the last pane the last pane in the previous scripture pane settings
- Open a project with the word alignment tool and the scripture pane should display the targetLangugague then the greek and at the end any carryover bible resource that was previously set if found.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/word-alignment-tool/13)
=> Display the Greek & the target language in the Scripture Pane by default 

__tests__/DropBoxArea.test.js, __tests__/WordBankArea.test.js, __tests__/fixtures/luke/1.json, package-lock.json, package.json, src/components/DropBoxArea/index.js, src/components/WordBankArea/index.js
Issue: https://github.com/unfoldingWord-dev/translationCore/issues/3486
Fixes:
DropBoxArea/index.js & WordBankArea/index.js - fixes for verses without alignment data
Needs to be tested with PR: https://github.com/unfoldingWord-dev/translationCore/pull/3492
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/word-alignment-tool/14)
=> Bugfix #3486/wA Tool crashes on missing alignment data for verse.

src/Container.js
Scroll bug when aligning words at the bottom after scrolling down, its scrolled to the top.
- Scrolling to the top was happening while aligning words in the same verse.
- Try finding multiple verses that you can scroll down with.
- Align words at the bottom and they shouldn't scroll to the top.
- Switch to another verse that can scroll, and it shouldn't stay scrolled down to the bottom and scrolls back to the top like it should.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/word-alignment-tool/15)
=> Only scroll to top when changing verses not the opposite.

src/Container.js
This PR Addresses:
- Word Alignment tool will not open on fresh install
- Scripture Pane settings didn't exist and need to check before using them.
To Test:
BEFORE YOU CHECK OUT THE BRANCH:
- Nuke your `~/Library/Application Settings/translationCore` folder and launch tC.
- Load any project, then load word alignment tool, it should crash with the warning that "Cannot read property 'currentPaneSettings' of undefined"
- Ensure that tool doesn't load and presents you with the tools page with console error.
DO NOT CONTINUE UNTIL YOU CAN RECREATE THE ABOVE!
AFTER YOU CHECK OUT THE BRANCH:
- Repeat the above and errors should be gone, tool should load properly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> Fixes word alignment tool on fresh install, no scripture pane settings

src/Container.js
Update bhp references to ugnt.
Should automatically switch to UGNT.  Check settings.json -  if `bhp` is in `currentPaneSettings`, then it should be replaced with `ugnt` when WA is opened.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/word-alignment-tool/18)
=> bugfix 3273/UGNT QA Fail

src/Api.js, src/components/Container.js, src/utils/usfmHelpers.js
- Now removing USFM markers that were previously unsupported
- Load [jhn.usfm.zip](https://github.com/translationCoreApps/wordAlignment/files/2168503/jhn.usfm.zip) w/ wA tool
- Go to John 1:23
- No USFM markers should show up as words in the wA tool
- Aligning all the words from the word list should show the complete check mark in the menu.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/wordalignment/49)
=> Now removing USFM markers that were previously unsupported

src/components/Container.js, src/components/MAPControls.js
related to https://github.com/unfoldingWord-dev/translationCore/issues/4706
- The reject and accept buttons are disabled when there no alignment suggestions.
- open a verse with suggestions and ensure the two buttons mentioned above are **enabled**
- remove the suggestions (any way you wish) and ensure the two buttons are **disabled**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/wordalignment/59)
=> MAP buttons are disabled when there no suggestions

src/Api.js, src/__tests__/api.js
Re: @mannycolon 
- This fixes a bug in saving the alignment data.
The visual affect of this bug would be: re-opening a project with invalid alignments in another chapter would always show a dialog indicating some alignments were reset.
- 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/wordalignment/62)
=> fixed bug saving alignment data for the entire book

src/Api.js, src/state/actions/index.js
-
- Open the following projects with wA tool and they should not display any broken links in the menu
- https://git.door43.org/ult-pre-alignment/en_tit
-  [en_tstf_tit_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/2214722/en_tstf_tit_book.zip) 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/wordalignment/64)
=> Fixed bug that would cause to wrongly display broken links in the wA tool

src/state/reducers/alignments/__tests__/render_alignments.test.js, src/state/reducers/alignments/render.js
Related to https://github.com/unfoldingWord-dev/translationCore/issues/4800
- This fixes a bug in the alignment renderer that was allowing target tokens to be used more than once under certain situations.
- See the instructions in https://github.com/unfoldingWord-dev/translationCore/issues/4800
- The token should no longer be suggested.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/wordalignment/66)
=> Fixes displaying invalid alignment suggestions

src/Api.js, src/components/Container.js
Related to https://github.com/unfoldingWord-dev/translationCore/issues/4911
- This fixes a bug causing wA to crash when opening a verse without any source/target text.
- See issue for steps to test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/wordalignment/70)
=> fixed crashing when source text is empty

src/Api.js
- when loading chapters, only numerical verses are loaded (i.e. front matter will be skipped)
- test with tCore release-v1.0.0 branch.
- see original issue https://github.com/unfoldingWord-dev/translationCore/issues/5041.  Should be able to open project in both WA and TW.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/wordalignment/79)
=> Bugfix 5041/Fix for Loading Projects with front matter

src/Api.js
Related to https://github.com/unfoldingWord-dev/translationCore/issues/5277. Discovered while working on https://github.com/unfoldingWord-dev/translationCore/issues/5174
This fixes a performance regression.
-
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/wordalignment/85)
=> Fixes performance regression

src/Api.js
related to https://github.com/unfoldingWord-dev/translationCore/issues/5259
- Streamlines the alert code and uses ignorable alerts.
- Edit a verse in wA or tW such that it invalidates some alignments.
- Once the edit has been made an alert will be displayed warning of the reset alignments with an option to ignore further warnings.
- Edit again and notice no alert is displayed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/wordalignment/91)
=> Updates the api to use ignorable alerts

src/Api.js, src/__tests__/api-progress.js
Related to https://github.com/unfoldingWord-dev/translationCore/issues/5692 and https://github.com/unfoldingWord-dev/translationCore/issues/5694 and https://github.com/unfoldingWord-dev/translationCore/issues/5698 and https://github.com/unfoldingWord-dev/translationCore/issues/5699 and https://github.com/unfoldingWord-dev/translationCore/issues/5339
- This updates the progress calculation to count fully aligned verses or verse that have been toggled complete.
> I believe this will close all of the above issues.
- align all the target tokens to all of the source tokens in a verse. (This will automatically toggle the verse as complete).
- check the progress on the tool card.
- untoggle the verse but keep it aligned. The progress should remain the same.
- toggle a different verse that is not …
=> Fixed progress calculation

src/Api.js
Related to https://github.com/unfoldingWord-dev/translationCore/issues/5692
- Fixes fully aligned verses not showing as complete in wA
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/wordalignment/156)
=> mark fully alligned verses as complete durring validation

src/components/AlignmentCard/index.js, src/components/AlignmentGrid.js, src/components/Container.js
- Fix Primary Word div height for Hebrew in Alignment Area so it matches size of drop area below
- Center Hebrew text in Primary Word div.
- test using https://github.com/unfoldingWord-dev/translationCore/pull/5841
- can use this OT project https://git.door43.org/lrsallee/en_ult_rut_book
- in WA make sure Scripture Pane for Hebrew and alignment area matches screenshots at bottom of https://github.com/unfoldingWord-dev/translationCore/issues/5789
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/wordalignment/164)
=> Bugfix 5789/Fix Primary Word height for Hebrew in Alignment Area

src/Api.js, src/__tests__/api.js
- this PR should fix issues 1 & 2 in #3562, inserting words should cause invalidation when alignment is complete.
- test with tCore branch release-v1.1.3
- look at failures at bottom of https://github.com/unfoldingword-dev/translationcore/issues/3562
- this PR should fix issues 1 & 2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/wordalignment/167)
=> Bugfix mcleanb 3562

src/Api.js, src/__tests__/api.js, src/containers/GroupMenuContainer.js, src/locale/English-en_US.json
- If either a target word is unaligned or an original language word is unaligned, this filter will display it. 
- Just open any project and select wA tool, once a verse is completely aligned it should no longer show if the `Unaligned` filter is selected.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/wordalignment/177)
=> Added Unaligned Words Filter

src/state/actions/__tests__/actions.test.js, src/state/actions/index.js
- Fix to move target words when merging alignments if source alignment had single Primary word.
- test with latest develop
- open a project in WA.
- try all examples in https://github.com/unfoldingword-dev/translationcore/issues/6148 to make sure they work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/wordalignment/187)
=> Feature 6148/

src/components/MAPControls.js, src/locale/English-en_US.json
- Verbiage change for #5938
- Load a project and go to the WA tool
- Mouse over the suggestion buttons at the bottom. They should say "Refresh suggestions", "Accept all suggestions" and "Reject all suggestions" (no longer have "MAP-generated" in the string)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/wordalignment/191)
=> Fixes #5938 - verbiage change for suggestion buttons tooltips

src/components/Container.js, src/components/WordList/__tests__/__snapshots__/DroppableWordList.test.js.snap, src/components/WordList/index.js
QAFail fix for https://github.com/unfoldingWord-dev/translationCore/issues/5930
- Use this branch in tC_apps/wordAlignment with the latest develop version of tC
- Run tC, Load a project, go into WA
- Select word(s) in the word bank. Now clicking on the following should clear those selections: scripture pane expansion, add bible to scripture pane, refresh/accept/reject (when not disabled), Alignment complete on and off.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/wordalignment/197)
=> QAFail #5930 - Deselect WordBank words on map button clicks

package-lock.json, src/Api.js, src/__tests__/api.js, src/containers/GroupMenuContainer.js
- PR fixes the word alignment tool not showing verse edits after external edits
- Download the following:
[project](https://github.com/unfoldingWord-dev/translationCore/files/3157968/en_test_1ti_book.zip)
[usfm](https://github.com/unfoldingWord-dev/translationCore/files/3157971/55-1TI-all.usfm.zip)
- Overwrite the project with the USFM file
- Open wA tool, ensure verses 1:3, 1:20 show as having a verse edit and being unaligned in group menu
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/wordalignment/194)
=> Fix Loading Verse Edits In Group Menu

src/Api.js
- fixes problem that edits in a checking tool would not immediately update state in group menu in WA.
- fix to clear groupMenu reducer every time WA is launched
- test using build attached at bottom of https://github.com/unfoldingWord-dev/translationCore/pull/6468
- import this project from usfm [57-TIT.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/3591552/57-TIT.usfm.zip)
- open WA tool
- then open TN tool and edit verse
- go back to WA and make sure edited verse shows both edited and invalidated on group menu
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/wordalignment/214)
=> Bugfix 6424/Clear group menu reducer every time WA is launched

.eslintrc, package.json, src/Api.js, src/__tests__/api.js, src/components/AlignmentCard/__tests__/AlignmentCard.test.js, src/components/AlignmentCard/index.js, src/components/Container.js, src/components/PrimaryToken.js, src/components/SecondaryToken.js, src/components/WordList/WordList.js, src/components/WordList/__tests__/DroppableWordList.test.js, src/components/WordList/__tests__/WordList.test.js, src/components/WordList/index.js, src/components/__tests__/AlignmentGrid.test.js, src/components/__tests__/MAPControls.test.js, src/containers/GroupMenuContainer.js, src/state/actions/__tests__/actions.test.js, src/state/actions/__tests__/mocked.actions.test.js, src/state/actions/index.js, src/state/reducers/__mocks__/index.js, src/state/reducers/alignments/__tests__/alignments.test.js, src/state/reducers/alignments/__tests__/suggestions.test.js, src/state/reducers/alignments/alignment.js, src/state/reducers/alignments/index.js, src/state/reducers/alignments/renderedAlignments.js, src/state/reducers/alignments/verse.js
- make change so that invalidation is not reset when you navigate to verse, but when you either complete the alignments or when you toggle alignment complete.
- use the test build below.  You can use this project that has a lot of invalidations: https://git.door43.org/photonomad1/en_prct_tit_book
- import and launch wa tool.
- pick an invalidated verse, when you switch to it you should not see invalidation clear.
- toggle alignment complete and you should see invalidation clear
- pick another invalidated verse.  Click on the accept button for suggested alignments.  Now Drag unaligned words until alignment is complete.  You should see alignment complete check come on and invalidation flag clear at the same time.
=> Feature 5520/Remove invalidation when alignment completed

src/Api.js, src/__tests__/api.js
- fix for empty verse - don't invalidate.
- test with attached build below
- do local import this project: [en_act.T.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2721619/en_act.T.usfm.zip).  Will see warning the 19:41 is missing.
- launch WA - will see invalidation warning.
- toggle group menu filter for invalidated.  Should only see acts 3:1,  acts 19:41 should not be toggled invalidated since it is an empty verse.
=> Bugfix 5640/Do not invalidate empty verse

src/components/AlignmentCard/__tests__/__snapshots__/AlignmentCard.test.js.snap, src/components/Container.js, src/components/WordCard/__tests__/__snapshots__/WordCard.test.js.snap, src/components/WordCard/index.js, src/components/WordList/__tests__/__snapshots__/DroppableWordList.test.js.snap, src/components/WordList/__tests__/__snapshots__/WordList.test.js.snap, src/components/__tests__/__snapshots__/AlignmentGrid.test.js.snap
- changed wordbank width to be variable from 100 to 400px (previously was fixed at 160px).
- changed word cards so oversized text will show ellipsis instead of overflowing card
- can use test build attached below.
- for testing can use this project with long greek words: https://git.door43.org/Door43-Catalog/el-x-koine_ugnt/raw/branch/master/57-TIT.usfm
- open project in WA
- switch between verses and should see wordbank width expand to match size of the longest word.  
- edit a verse to make a word very-very long.  Word bank should stop a 400px and word should not overflow word card - instead should see it truncated with ellipsis.
=> Feature 5440/Make WordBank variable width

src/components/AlignmentCard/__tests__/__snapshots__/AlignmentCard.test.js.snap, src/components/WordCard/__tests__/__snapshots__/WordCard.test.js.snap, src/components/WordCard/index.js, src/components/WordList/__tests__/__snapshots__/DroppableWordList.test.js.snap, src/components/WordList/__tests__/__snapshots__/WordList.test.js.snap, src/components/WordList/index.js, src/components/__tests__/__snapshots__/AlignmentGrid.test.js.snap
- Corrects a bug where dragging words would cause the wordbank to resize. See https://github.com/unfoldingWord/translationCore/issues/6633
- Adds support for very long words in the wordbank. Long words now break and wrap. See https://github.com/unfoldingword/translationcore/issues/6627
- Open a project in the wordAlignment tool and drag a word. The wordbank should maintain it's width.
=> fix wordbank resizing when words are dragged

src/components/AlignmentCard/__tests__/__snapshots__/AlignmentCard.test.js.snap, src/components/WordCard/__tests__/__snapshots__/WordCard.test.js.snap, src/components/WordCard/index.js, src/components/WordList/WordList.js, src/components/WordList/__tests__/__snapshots__/DroppableWordList.test.js.snap, src/components/WordList/__tests__/__snapshots__/WordList.test.js.snap, src/components/WordList/index.js, src/components/__tests__/__snapshots__/AlignmentGrid.test.js.snap
- Related to https://github.com/unfoldingword/translationcore/issues/6627 and https://github.com/unfoldingword/translationcore/issues/6633
- Restored original behavior where the wordbank is flexible up to a maximum width.
- Words larger than the maximum width have a tooltip.
- The wordbank does not change size when dragging words in/out of it.
-
=> Bugfix joel resizing

src/Api.js, src/common/constants.js, src/state/actions/verseEditActions.js
- change updateVerseEditStatesAndCheckAlignments() to call validateVerse in tW and tN through API to validate selections so tW and tN can do the validation and then update the group data with latest verse edits.
- can test using tCore and WA branches `bugfix-mcleanb-6675.2`
- in tN or tW: using scripture pane, edit different verse than current verse and it should mark all checks in the edited verse as edited
- in WA edit a verse and should see verse edit indications in tW and tN.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/wordalignment/253)
=> Bugfix 6675/fix verse edit in tools

src/components/SecondaryToken.js, src/components/WordCard/index.js, src/components/WordList/WordList.js, src/components/WordList/__tests__/__snapshots__/DroppableWordList.test.js.snap, src/components/WordList/__tests__/__snapshots__/WordList.test.js.snap
- Related to https://github.com/unfoldingWord/translationCore/issues/6627
- Decreases padding between words in the wordbank.
- Disables tooltips when a word is being dragged.
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/wordalignment/254)
=> Hide tooltip when dragging target words

src/Api.js
- clear contextId when Project is changed
- this will fix scenarios 3 & 4 from https://github.com/unfoldingWord/translationCore/issues/6790. Crashes due to changing projects when contextId of old project is outside range of new project.
- scenario 1 & 2 will be fixed by Joel's tc-ui-toolkit PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/wordalignment/265)
=> Bugfix 6790/Fix to clear contextId when Project is changed

src/components/Container.js
- Related to https://github.com/unfoldingword/translationcore/issues/6237.... but not really
- This corrects a parameter to wordmap to disable verbose logging. This makes it a bit easier to read the console logs.
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/wordalignment/259)
=> disabled verbose warnings from wordmap

src/Api.js
- Fix to clear out all group data reducers when tool is connected to project
- test with tC develop branch.  SHould fix the fail at bottom of issue
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/wordalignment/266)
=> Bugfix 6790/Fix to clear out all group data reducers

src/components/Container.js
- fix for Hebrew fonts being clipped and too bold
- test with tC build bugfix-mcleanb-6984
- in OT projects in wA  should not see the clipping of Hebrew in Alignment grid area and text should be less bold:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/wordalignment/281)
=> Bugfix 6984/Fix for Hebrew fonts being clipped and too bold

src/components/SecondaryToken.js, src/components/ThemedTooltip.js, src/components/WordCard/index.js, src/components/WordList/WordList.js, src/components/WordList/__tests__/__snapshots__/DroppableWordList.test.js.snap, src/components/WordList/index.js
- Related to https://github.com/unfoldingword/translationcore/issues/7011
- fix tooltips displaying any time the mouse hovered over it.
- connected the new font size setting to wordbank tooltips so they scale as well.
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/wordalignment/284)
=> Fixes word tooltips when using arabic font

package-lock.json, package.json, src/components/ThemedTooltip.js, src/components/WordList/__tests__/__snapshots__/DroppableWordList.test.js.snap
- fix arrow on word bank item hover
- test with tC branch `bugfix-mcleanb-7034`
- in wA, test hover text in group menu when selection text overflows - arrow should not move
- in wA, test hover text in word bank when word overflows - arrow should not move
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/wordalignment/294)
=> Bugfix 7034/fix arrow on word bank item hover - should not move

src/components/AlignmentCard/__tests__/__snapshots__/AlignmentCard.test.js.snap, src/components/AlignmentCard/index.js, src/components/AlignmentGrid.js, src/components/PrimaryToken.js, src/components/WordCard/WordOccurrence.js, src/components/WordCard/__tests__/__snapshots__/WordCard.test.js.snap, src/components/WordCard/index.js, src/components/WordList/__tests__/__snapshots__/DroppableWordList.test.js.snap
-
- checkout `bugfix-mannycolon-7033` branch in wa submodule
- verify that the word occurrence number in the word cards don't overflow when resizing the text in the alignment grid
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/wordalignment/293)
=> Fixed overflowed occurrence number on wA tool word cards
